# Required metadata
sonar.projectKey={projectKey}
sonar.projectName={projectName}

sonar.organization=segurosbolivar
sonar.host.url=https://sonarcloud.io
# Comma-separated paths to directories with sources (required)
sonar.sources=./

# Language
sonar.language=js
sonar.profile=node
# Encoding of sources files
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**, coverage/**, public/**, build/**, **/__tests__/**, util-testing/**, **/polyfills.ts, **/main.ts, **/bootstrap.ts, **.html, **.css, **.scss, **.config.*, **/index.ts, **/setup-jest.ts, **/*.mock.ts, **/environments/**, **.module.ts
sonar.coverage.exclusions= **.module.ts, **.spec.ts, **.test.ts, **.scss, **.css, **.html, **.config.*, **/index.ts, **/setup-jest.ts, **/environments/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.scanner.force-deprecated-java-version=true
